// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEVIKqaboC1c9NU7ixoUOEQkk0ideziVY',
    appId: '1:141361346509:web:31c2976a30684c7ede3684',
    messagingSenderId: '141361346509',
    projectId: 'alvaro-assignment7',
    authDomain: 'alvaro-assignment7.firebaseapp.com',
    storageBucket: 'alvaro-assignment7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCXpuRjAPhbZ0KeWCNzJYxiQ3LHKCsiOQ',
    appId: '1:141361346509:android:edc3665c22cbe901de3684',
    messagingSenderId: '141361346509',
    projectId: 'alvaro-assignment7',
    storageBucket: 'alvaro-assignment7.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEVIKqaboC1c9NU7ixoUOEQkk0ideziVY',
    appId: '1:141361346509:web:12461cad5850c0b5de3684',
    messagingSenderId: '141361346509',
    projectId: 'alvaro-assignment7',
    authDomain: 'alvaro-assignment7.firebaseapp.com',
    storageBucket: 'alvaro-assignment7.appspot.com',
  );
}
